- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - xubuntu-desktop
    - chromium-browser
    - vim-gtk
    - openjdk-7-jdk

- command: dpkg-reconfigure lightdm

- name: permit anyone to start the x server
  lineinfile: dest=/etc/X11/Xwrapper.config
    regexp='^#?allowed_users='
    line='allowed_users=anybody'
    state=present

- name: lightdm auto login
  lineinfile: dest=/etc/lightdm/lightdm.conf.d/10-xubuntu.conf
    regexp='^#?autologin-user='
    line='autologin-user=antoine'
    state=present

- name: lightdm auto login
  lineinfile: dest=/etc/lightdm/lightdm.conf.d/10-xubuntu.conf
    regexp='^#?autologin-user-timeout='
    line='autologin-user-timeout=0'
    state=present

- name: lightdm auto login
  lineinfile: dest=/etc/lightdm/lightdm.conf.d/10-xubuntu.conf
    regexp='^pam-service='
    line='pam-service=lightdm-autologin'
    state=present

- name: lightdm disallow user switch
  lineinfile: dest=/etc/lightdm/lightdm.conf.d/10-xubuntu.conf
    regexp='^allow-user-switching='
    line='allow-user-switching=false'
    state=present